### ISSUE TITLE
Too high mob spawning rate

### ISSUE THREAD

**Issue by Barteks2x** [OpenCubicChunks/CubicChunks#33] opened 2016-06-17 23:22 UTC

**Comment by Boreeas** [comment] 2016-09-27 16:13
The way it appears to me, spawn rate seems sensible. How did the too-high-rate manifest?

**Comment by Niko-sk2x** [comment] 2017-01-08 14:35
Can someone actually test if mob spawning rates are similar to vanilla? If they are close enough, this issue can be closed.

**Comment by Niko-sk2x** [comment] 2017-04-30 23:37
Can't reproduce for now, closing until it comes up again.

**Comment by Niko-sk2x** [comment] 2017-06-19 17:47
I haven't seen anyone mention it to be an issue, so it probably works correctly. Closing for now.

**Closed by Niko-sk2x** 2017-06-19 17:47 UTC
Labels: Bug

**Comment by BaccarWozat** [comment] 2017-06-22 08:15
It doesn't seem to be an issue very often. Sometimes with Quark there are a few extra mobs, mostly guardians.

The screenshot below (no other mods) shows 460+ squid all spawning at once. I don't know what the usual number is in vanilla at render distance 16/16. Forge 2315 and CC build 265. None of the logs report anything other than the usual File IO Thread/DEBUG.

![2017-06-22_03 03 46](https://user-images.githubusercontent.com/8357501/27423706-1b0f903a-56f8-11e7-94f6-054191c3cc09.png)

**Comment by Niko-sk2x** [comment] 2017-06-22 10:07
Vanilla also sometimes tends to spawn unreasonable amountes of squids sometimes (and sometimes, when you want to find them, there are none), but this seems a bit too high.
