### ISSUE TITLE
Sometimes some chunk renderers don't update

### ISSUE THREAD

**Issue by Barteks2x** [OpenCubicChunks/CubicChunks#68] opened 2016-10-15 04:17 UTC
This may be vanilla bug.

**Comment by Niko-sk2x** [comment] 2016-11-21 16:03
I didn't see it happen in a long time. I'm not sure what caused it, closing until it happens again.

**Comment by Niko-sk2x** [comment] 2016-11-23 15:47
I found the issue again

**Comment by Niko-sk2x** [comment] 2016-11-27 14:39
Found it again, but this time different: a whole layer of chunks didn't render instead of just one chunk. This happened while flying up and down in tunnel make by TNT.

**Comment by Foghrye4** [comment] 2017-01-07 21:42
Also saw it. I think this caused by cube render updates when they receive data from server. To increase performance Minecraft render chunk in GL lists, which are later called by renderer. Because it takes some time to refresh those lists in time they are re-rendered they became invisible. A simplest way to fix it - increase server cube view radius to higher value than client cube view distance.

But this is just a theory.

**Comment by Niko-sk2x** [comment] 2017-01-07 22:37
The problem isn't they they just take a lot of time to update, the problem is that they *never* actually update. I've seen it several times, mainly after using commands to create deep pillar of TNT, exploding it all, falling down, and then slowly flying up again.

**Comment by Niko-sk2x** [comment] 2017-05-19 18:36
I've been told it's vanilla bug. Since vanilla bugtrackerr seems to be confused about different kinds of chunk rendering issues and merged them all into one or 2, I won't link to vanilla issue.

**Closed by Niko-sk2x** 2017-05-19 18:36 UTC
Labels: Bug
